# Generated by Django 6.0 on 2026-04-21 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_intel_server', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('is_malformed', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('soc', models.IntegerField(blank=True, null=True)),
                ('soh', models.IntegerField(blank=True, null=True)),
                ('tte', models.IntegerField(blank=True, null=True)),
                ('ttf', models.IntegerField(blank=True, null=True)),
                ('cycles', models.IntegerField(blank=True, null=True)),
                ('lowbattery', models.BooleanField(default=False)),
                ('vbat', models.IntegerField(blank=True, null=True)),
                ('ibat', models.IntegerField(blank=True, null=True)),
                ('vchg', models.IntegerField(blank=True, null=True)),
                ('vsys', models.IntegerField(blank=True, null=True)),
                ('ichg', models.IntegerField(blank=True, null=True)),
                ('avgi', models.IntegerField(blank=True, null=True)),
                ('avgpwr', models.IntegerField(blank=True, null=True)),
                ('gtmp', models.IntegerField(blank=True, null=True)),
                ('ctmp', models.IntegerField(blank=True, null=True)),
                ('btmp', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('wake', models.CharField(blank=True, max_length=50, null=True)),
                ('adapter', models.BooleanField(default=False)),
                ('safety', models.CharField(blank=True, max_length=20, null=True)),
                ('battstat', models.CharField(blank=True, max_length=20, null=True)),
                ('chgflags', models.CharField(blank=True, max_length=20, null=True)),
                ('faultflags', models.CharField(blank=True, max_length=20, null=True)),
                ('chgstat', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rawframeupload',
            name='linked_diagnostic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_frames', to='insect_intel_server.devicediagnostic'),
        ),
        migrations.CreateModel(
            name='DeviceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/%Y/%m/%d/')),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('linked_diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='insect_intel_server.devicediagnostic')),
            ],
        ),
    ]
