# Generated by Django 6.0 on 2026-04-21 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_intel_server', '0002_devicediagnostic_rawframeupload_linked_diagnostic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicediagnostic',
            name='critical_msg_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deviceimage',
            name='device_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawframeupload',
            name='device_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
