# Generated by Django 6.0 on 2026-04-22 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insect_intel_server', '0003_devicediagnostic_critical_msg_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicediagnostic',
            name='critical_msg_sent',
        ),
        migrations.RemoveField(
            model_name='devicediagnostic',
            name='tte',
        ),
        migrations.RemoveField(
            model_name='devicediagnostic',
            name='ttf',
        ),
    ]
