# Generated by Django 6.0 on 2026-04-22 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insect_intel_server', '0004_remove_devicediagnostic_critical_msg_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicediagnostic',
            name='is_malformed',
        ),
    ]
