# Generated by Django 6.0 on 2026-04-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_intel_server', '0006_devicecommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicediagnostic',
            name='cam_res',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='cfg_ichg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='cfg_iindpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='cfg_iprechg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='cfg_iterm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='cfg_vindpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='cfg_vreg',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='cfg_vsysmin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='cfg_wake_interval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='device_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='last_comm_epoch',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='lte_sent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='lte_sig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='lte_stat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='net',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='sd_free',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='sd_pres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='sim_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='sim_pres',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicediagnostic',
            name='wifi_stat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
