# Generated by Django 6.0 on 2026-04-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_intel_server', '0007_devicediagnostic_cam_res_devicediagnostic_cfg_ichg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceimage',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deviceimage',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deviceimage',
            name='image_file',
            field=models.ImageField(height_field='height', upload_to='images/%Y/%m/%d/', width_field='width'),
        ),
    ]
