# Generated by Django 6.0 on 2026-04-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insect_intel_server', '0008_deviceimage_height_deviceimage_width_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=50, null=True)),
                ('upload_type', models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic Telemetry'), ('IMAGE', 'Device Image'), ('RAW_FRAME', 'Raw Frame')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
